DELETE http://127.0.0.1:8080/books
Content-Type: application/json

{
  "name": "cat"
}

###
POST http://127.0.0.1:8080/books
Content-Type: application/json

{
  "name": "REpka",
  "pages": 6542
}

###
GET http://127.0.0.1:8080/books
Accept: application/json

###

PUT http://127.0.0.1:8080/books
Content-Type: application/json

{
  "name": "REpka",
  "pages": 1
}